#!/bin/bash

# Set minimal environment for testing
export VUS=2
export ZONES_TOTAL=1
export RECORDS_PER_ZONE=10
export BATCH_NUM=1
export TEST_DURATION_SEC=0  # Use count-based test for quick testing
export PRE_GENERATE_VERTEX_DATA=true
export SHUFFLE_PROCESSING_ORDER=false

# Real credentials for testing
export GOOGLE_APPLICATION_CREDENTIALS_FILE="sa2.json"
export PROJECT_ID="span-cloud-testing"
export INSTANCE_ID="irahul-load-test"
export DATABASE_ID="graphdb"

echo "Starting Jaeger in Docker..."
docker-compose up -d jaeger

echo "Waiting for Jaeger to be ready..."
sleep 5

echo "Building and running the test..."
go build -o graph-load .

echo "Running write-vertex-improved test with tracing..."
./graph-load -test write-vertex-improved

echo ""
echo "Test completed. You can view traces at http://localhost:16686"
echo "Service name: spanner-graph-test"
echo ""
echo "You should now see built-in Spanner client traces including:"
echo "- cloud.google.com/go/spanner operations (Apply, Commit, etc.)"
echo "- Session acquisition and management"
echo "- gRPC calls to Spanner APIs"
echo "- Internal Spanner client operations"
echo ""
echo "These traces are automatically generated by the Spanner client library"
echo "and provide detailed visibility into database operations without custom code." 